### ISSUE TITLE
fragment选择报空

### ISSUE THREAD

**Issue by YuedongMa** [linchaolong/ImagePicker#1]
运行例子fragment报错
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
                                                       at com.linchaolong.android.imagepicker.ImagePicker.getRealPathFromUri(ImagePicker.java:249)
                                                       at com.linchaolong.android.imagepicker.ImagePicker.handleUri(ImagePicker.java:380)
                                                       at com.linchaolong.android.imagepicker.ImagePicker.handlePickImageInner(ImagePicker.java:353)
                                                       at com.linchaolong.android.imagepicker.ImagePicker.handlePickImage(ImagePicker.java:339)
                                                       at com.linchaolong.android.imagepicker.ImagePicker.onActivityResultInner(ImagePicker.java:226)
                                                       at com.linchaolong.android.imagepicker.ImagePicker.onActivityResult(ImagePicker.java:199)
                                                       at com.linchaolong.android.imagepicker.demo.TestFragment.onActivityResult(TestFragment.java:41)
                                                       at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
``

**Comment by linchaolong** [comment]
已修复，compile 'com.linchaolong.android:imagepicker:1.1'
