### ISSUE TITLE
 imagePicker.startCamera(this, callback)

### ISSUE THREAD

**Issue by KucherenkoIhor** [linchaolong/ImagePicker#12]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                  at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:591)
                                                                  at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:565)
                                                                  at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:403)
                                                                  at com.linchaolong.android.imagepicker.Utils.getContentUri(Utils.java:31)
                                                                  at com.linchaolong.android.imagepicker.Utils.getIntentUri(Utils.java:24)
                                                                  at com.linchaolong.android.imagepicker.cropper.CropImage.getCameraIntent(CropImage.java:218)
                                                                  at com.linchaolong.android.imagepicker.ImagePicker.startCamera(ImagePicker.java:105)

**Comment by QiaoJim** [comment]
I got the same error. Any solutions? 
thanks a lot
