### ISSUE TITLE
和之前设置的provider冲突，有什么解决方式么？

### ISSUE THREAD

**Issue by hope320** [linchaolong/ImagePicker#17]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                               at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:584)
                                                               at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:558)
                                                               at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
                                                               at com.linchaolong.android.imagepicker.Utils.getContentUri(Utils.java:31)
                                                               at com.linchaolong.android.imagepicker.Utils.getIntentUri(Utils.java:24)
                                                               at com.linchaolong.android.imagepicker.cropper.CropImage.getCameraIntents(CropImage.java:240)
                                                               at com.linchaolong.android.imagepicker.cropper.CropImage.getPickImageChooserIntent(CropImage.java:177)
                                                               at com.linchaolong.android.imagepicker.ImagePicker.startChooser(ImagePicker.java:71)
                                                               at com.hope.md.ImagePickerActivity.lambda$onCreate$0$ImagePickerActivity(ImagePickerActivity.java:33)
                                                               at com.hope.md.ImagePickerActivity$$Lambda$0.onClick(Unknown Source)
                                                               at android.view.View.performClick(View.java:5647)
                                                               at android.view.View$PerformClick.run(View.java:22462)
                                                               at android.os.Handler.handleCallback(Handler.java:754)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:163)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6379)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by fjg2016** [comment]
自己重写一个provider，不要实现任何方法，在manifest中把之前的provider改成自定义的这个包名.provider(自己重写的provider的类名)
